<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Domain/Todo.fs" />
    <Compile Include="Domain/TodoList.fs" />
    <Compile Include="Infrastructure/FileSystem.fs" />
    <Compile Include="Infrastructure/JsonStorage.fs" />
    <Compile Include="Infrastructure/TodoStorage.fs" />
    <Compile Include="Application/Commands.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
